In [ ]:
#EXERCICE 1

import numpy as np

tab = np.arange(10)
print(tab)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
#EXERCICE 2

import numpy as np

liste = [3.14, 2.17, 0, 1, 2]

tab = np.array(liste, dtype=int)
print(tab)

[3 2 0 1 2]


In [3]:
#EXERCICE 3

import numpy as np

tab = np.arange(1, 10).reshape(3, 3)
print(tab)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#EXERCICE 4

import numpy as np

tab = np.random.rand(4, 5)
print(tab)

[[0.1054323  0.67139966 0.25250118 0.31768338 0.18710624]
 [0.86980881 0.19648496 0.86930236 0.19688619 0.3586646 ]
 [0.88859075 0.96530291 0.05445835 0.54417947 0.89929838]
 [0.82671559 0.90514854 0.63114273 0.32596778 0.23707511]]


In [5]:
#ZXERCICE 5

import numpy as np

array = np.array([[21, 22, 23, 22, 22],
                  [20, 21, 22, 23, 24],
                  [21, 22, 23, 22, 22]])

deuxieme_ligne = array[1]

print(deuxieme_ligne)

[20 21 22 23 24]


In [6]:
#EXERCICE 6

import numpy as np

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

inverse = array[::-1]
print(inverse)

[9 8 7 6 5 4 3 2 1 0]


In [8]:
#EXERCICE 7

import numpy as np

matrice = np.eye(4)
print(matrice)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
#EXERCICE 8

import numpy as np

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

somme = np.sum(array)
moyenne = np.mean(array)

print(f"Sum: {somme}, Average: {moyenne}")

Sum: 45, Average: 4.5


In [9]:
#EXERCICE 9

import numpy as np

tab = np.arange(1, 21)

matrice = tab.reshape(4, 5)
print(matrice)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
#EXERCICE 10

import numpy as np

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

impairs = array[array % 2 == 1]
print(impairs)

[1 3 5 7 9]
